loom_cookie.category.*:
  type: config_entity
  label: 'LOOM Cookie Category config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    cookies:
      type: sequence
      label: 'Cookie names'
      sequence:
        type: string
    attachmentNames:
      type: sequence
      label: 'Attachment names'
      sequence:
        type: string
    scriptUrlRegexes:
      type: sequence
      label: 'Script URL regexes'
      sequence:
        type: string
    scriptBlockRegexes:
      type: sequence
      label: 'Script Block regexes'
      sequence:
        type: string
    scriptUrlRegexesClientSide:
      type: sequence
      label: 'Script URL regexes (blocked client-side)'
      sequence:
        type: string
    embedUrlRegexes:
      type: sequence
      label: 'Embed URL regexes'
      sequence:
        type: string
    embedMessage:
      type: text
      label: 'Embed Message'
    description:
      type: text_format
      label: 'Description'
      translatable: true
    detailedDescription:
      type: text_format
      label: 'Detailed description'
